config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  resources :users
  resources :todos
  root 'todos#index'
  get '/todo/calendar/:id', to: 'todos#calendar', as: 'calendar'
  get '/search', to: 'todos#index', as: 'search'
  get '/filter', to: 'todos#index', as: 'filter'

  get '/login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#delete'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
    belongs_to :user
    
    before_save :downcase_fields
    # after_initialize :init

    # def init
    #     self.done ||= false
    # end
    
    def downcase_fields
        self.tag.downcase
    end

end

app/models/user.rb
class User < ApplicationRecord
    has_many :todos
    
    validates :name, presence: true

    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    # protect_from_frogery with: exception

    def current_user
        User.find_by(id: session[:user_id])
    end

    helper_method :current_user

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(name: params[:session][:name])
    if user
      if user.authenticate(params[:session][:password])
        session[:user_id] = user.id
        redirect_to todos_path
      else 
        flash.now[:danger] = 'Bad name/password combination. '
        render 'new'
      end
    end
  end

  def delete
    session.delete(:user_id)
    @current_user = nil
    redirect_to login_path
  end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_todo, only: %i[ show edit update destroy ]
  skip_before_action :verify_authenticity_token

  require 'icalendar'

  # GET /todos or /todos.json
  def index
    if (current_user!= nil) 
      if params[:query] != nil 
        @todos = current_user.todos.where("name LIKE ? OR description LIKE ?", "%" + params[:query] + "%", "%" + params[:query] + "%")
      elsif params[:tag] != nil
        @todos = current_user.todos.where(tag: params[:tag])
      elsif params[:start_date] != nil && params[:end_date] != nil
        @todos = current_user.todos.where(due: (params[:start_date]..params[:end_date]))
      elsif params[:order] != nil
        order = params[:order].upcase
        @todos = current_user.todos.order('due ' + order)
      else
        @todos = current_user.todos.where(done: nil)
      end
      @tags = current_user.todos.distinct.pluck(:tag)
      @completed_todos = current_user.todos.where(done: true)
      @users = User.where(" name <> ? ",current_user.name)
    else
       redirect_to login_path
    end
  end

  # GET /todos/1 or /todos/1.json
  def show
  end

  # GET /todos/new
  def new
    @todo = Todo.new
  end

  # GET /todos/1/edit
  def edit
    if params[:done] != nil 
      todo = Todo.find_by_id(params[:id])
      todo.done = true;
      todo.save
      redirect_back(fallback_location: root_path)
    elsif params[:give_to] != nil 
      user = User.find_by(name: params[:give_to])
      post = Todo.find_by_id(params[:id])
      post.user = user
      post.save
      redirect_back(fallback_location: root_path)
    end
  end

  # POST /todos or /todos.json
  def create
    @todo = Todo.new(todo_params)
    @todo.user = current_user
    respond_to do |format|
      if @todo.save
        format.html { redirect_to @todo, notice: "Todo was successfully created." }
        format.json { render :show, status: :created, location: @todo }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todos/1 or /todos/1.json
  def update
    respond_to do |format|
      if @todo.update(todo_params)
        format.html { redirect_to @todo, notice: "Todo was successfully updated." }
        format.json { render :show, status: :ok, location: @todo }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todos/1 or /todos/1.json
  def destroy
    @todo.destroy
    respond_to do |format|
      format.html { redirect_to todos_url, notice: "Todo was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def calendar
    todo = Todo.find_by_id(params[:id])
    filename = todo.name

    cal = gen_calendar(todo)

    if params[:type] == 'vcs'
      cal.prodid = '-//Microsoft Corporation//Outlook MIMEDIR//EN'
      cal.version = '1.0'
      filename += '.vcs'
    else # ical
      cal.prodid = '-//Acme Widgets, Inc.//NONSGML ExportToCalendar//EN'
      cal.version = '2.0'
      filename += '.ics'
    end
    
    send_data cal.to_ical, type: 'text/calendar', disposition: 'attachment', filename: filename
    
  end

  def search
    @todos = Todo.first
    respond_to do |format|
      format.html { redirect_to todos_path }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo
      @todo = Todo.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def todo_params
      params.require(:todo).permit(:name, :description, :due, :tag)
    end

    def gen_calendar(todo)
      cal = Icalendar::Calendar.new
      cal.event do |e|
        e.dtstart     = Icalendar::Values::Date.new(todo.due)
        e.dtend       = Icalendar::Values::Date.new(todo.due + 1.hour)
        e.summary     = todo.name
        e.description = todo.description
        e.ip_class    = "PRIVATE"
      end
      cal
    end

    def redirect_to_default
      redirect_to root_path
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

      if @user.save
        redirect_to todos_path
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.fetch(:user, {}).permit(:name, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   <header>
      <% if current_user %>
        Hi <%= current_user.name %>
        |
        <%= link_to 'Log out', logout_path, method: :delete %>
      <% else %>
        <%= link_to 'Log in', login_path %>
        |
        <%= link_to 'Sign up', new_user_path %>
      <% end %>
    </header>

    <%= yield %>
  </body>
</html>

app/views/todos/_form.html.erb
<%= form_with(model: todo) do |form| %>
  <% if todo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(todo.errors.count, "error") %> prohibited this todo from being saved:</h2>

      <ul>
        <% todo.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :due %>
    <%= form.datetime_select :due %>
  </div>

  <div class="field">
    <%= form.label :tag %>
    <%= form.text_field :tag %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/todos/edit.html.erb
<h1>Editing Todo</h1>

<%= render 'form', todo: @todo %>

<%= link_to 'Show', @todo %> |
<%= link_to 'Back', todos_path %>

app/views/todos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Todos</h1>
<%= link_to 'show all...', controller: 'todos', action: 'index' %>

<h3>Search options</h3>
<div>
  <span id="search">
    <%= form_with url: search_url, method: :get do |form| %>
      <%= form.text_field :query %>
      <%= form.submit "Search" %>
    <% end %>
  </span>
  <span id="sel_tag">
    <%= form_with url: filter_url, method: :get do |form| %>
      <select name="tag" id="tags">
      <%= Array(@tags).each do |tag| %>
        <option value="<%= tag %>"><%= tag %></option>
        <% end %>
      </select>
      <%= form.submit "Filter" %>
    <% end %>
  </span>

  <span id="date_filter">
    <%= form_with url: filter_url, method: :get do |form| %>
      <%= form.date_field :start_date %>
      <%= form.date_field :end_date %>
      <%= form.submit "Filter" %>
    <% end %>
  </span>
</div>


<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th><%= link_to 'Due', filter_path(:order => "asc"), style: "color:white;" %></th>
      <th>Tag</th>
      <th>Done</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% Array(@todos).each do |todo| %>
      <tr>
        <td>
          <% @users.each do |user| %>
            <%= link_to raw("&#128073;") + " " + user.name, edit_todo_path(todo, :give_to => user.name) %> 
          <% end %>          
          <%=  todo.name %>
        </td>
        <td><%= todo.description %></td>
        <td><%= todo.due.strftime("%a, %H:%M %d/%m/%y") %></td>
        <td style="background-color: <%= todo.tag %>;"><%= todo.tag %></td>
        <td><%= if todo.done != true 
          "No"
          else 
          "Yes"
          end
        %></td>
        <td><%= link_to 'Download', calendar_path(todo, :type => 'ical')  %></td>
        <td><%= link_to 'Edit', edit_todo_path(todo) %></td>
        <td><%= link_to 'Destroy', todo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= 
          if (!todo.done)
            link_to 'Complete', edit_todo_path(todo, :done => true), style: 'color:green' 
          end
          %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Todo', new_todo_path %>

<hr>

<h3> Completed TODOs: </h3>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Done at</th>
      <th>Tag</th>
    </tr>
  </thead>

  <tbody>
    <% Array(@completed_todos).each do |todo| %>
      <tr>
        <td><%= todo.name %></td>
        <td><%= todo.description %></td>
        <td> <%= todo.updated_at.strftime("%a, %H:%M %d/%m/%y") %></td>
        <td><%= todo.tag %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/todos/new.html.erb
<h1>New Todo</h1>

<%= render 'form', todo: @todo %>

<%= link_to 'Back', todos_path %>

app/views/todos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @todo.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @todo.description %>
</p>

<p>
  <strong>Due:</strong>
  <%= @todo.due %>
</p>

<p>
  <strong>Tag:</strong>
  <%= @todo.tag %>
</p>

<%= link_to 'Edit', edit_todo_path(@todo) %> |
<%= link_to 'Back', todos_path %>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.label :name %> 
    <%= form.text_field :name %> 

    <%= form.label :password %>
    <%= form.password_field :password %>


    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>